# Generated by Django 5.2.1 on 2025-05-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SosDevice',
            fields=[
                ('device_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ping_time', models.DateTimeField(auto_now_add=True)),
                ('is_assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('assigned_device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sosdevice')),
            ],
        ),
    ]
